version: '3.7'

services:
  client:
    container_name: frontend_client
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/src

networks:
  default:
    name: football
